<?php

namespace Modules\cims_pm_pro\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ClientMasterDirector extends Model
{
    /** @use HasFactory<\Database\Factories\CimsDirectorFactory> */
    use HasFactory;

    protected $table = 'client_master_directors';

    protected $fillable = [
        'client_id',
        'person_id',
        'director_type_id',
        'director_status_id',
        'appointment_date',
        'resignation_date',
        'share_percentage',
        'share_type',
        'is_active',
        'number_of_director_shares',
        'director_type_name',
        'director_status_name',
        'date_engaged',
        'date_resigned',
        'citizenship',
        'identity_type',
        'identity_number',
        'gender',
        'date_of_birth',
        'date_of_issue',
        'person_status',
        'date_of_death',
        'ethnic_group',
        'disability',
        'passport_number',
        'passport_expiry',
        'country',
        'country_code',
        'nationality',
        'title',
        'initials',
        'surname',
        'firstname',
        'middlename',
        'known_as',
        'tax_number',
        'mobile_phone',
        'whatsapp_number',
        'office_phone',
        'other_phone',
        'email',
        'accounts_email',
        'marital_status',
        'marital_status_date',
        'sp_citizenship',
        'sp_identity_type',
        'sp_identity_number',
        'sp_date_of_birth',
        'sp_date_of_issue',
        'sp_person_status',
        'sp_gender',
        'sp_ethnic_group',
        'sp_disability',
        'sp_title',
        'sp_initials',
        'sp_tax_number',
        'sp_firstname',
        'sp_middlename',
        'sp_surname',
        'sp_known_as',
        'sp_mobile_phone',
        'sp_whatsapp_number',
        'sp_office_phone',
        'sp_other_phone',
        'sp_email',
        'sp_accounts_email',
        'complex_name',
        'address_line',
        'address_line_2',
        'suburb',
        'city',
        'postal_code',
        'province',
        'address_country',
        'latitude',
        'longitude',
        'bank_account_holder',
        'bank_name',
        'bank_branch',
        'bank_account_number',
        'bank_account_type',
        'bank_swift_code',
        'bank_account_status',
        'bank_date_opened',
        'notes',
        'profile_photo',
        'id_front_image',
        'id_back_image',
        'green_book_image',
        'update_image',
        'passport_image',
        'poa_image',
        'banking_image',
        'signature_image',
        'created_by',
    ];
}
